### ISSUE TITLE
[General] word wrap and padding in Dropdown

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/payvo-wallet#1016]
### Describe the refactor you'd like to request

**_Current implementation:_**

When you are selecting a currency on profile creation it has a lot of whitespaces so some of the items are listed in 2 lines:

![2lines](https://user-images.githubusercontent.com/25795454/153570539-7d863ff7-9300-4f1d-b914-d781eca55090.jpg)

Also as you can see the gap is pretty substantial here:

![pad](https://user-images.githubusercontent.com/25795454/153570781-c33adaf7-e64f-4e7b-8e96-a77809c912d4.png)

**_Expected behavior:_** 

It should all fit on 1 line instead of 2.

**Comment by dated** [comment]
Relevant discussion: https://cryptoarkproject.slack.com/archives/CJFKZSV61/p1644609440485859
