### ISSUE TITLE
[portfolio] large token value pushes dropdowns out of view

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1089]
### Describe the refactor you'd like to request

when you add a wallet to your portfolio that has a large amount of tokens, and decimals, it will not fit the width of the view anymore

<img width="387" alt="image" src="https://user-images.githubusercontent.com/35610748/156767910-38abf150-3381-46f7-b67d-b2bb8753bcb4.png">

there's also an issue with the dropdown icon not having a square outline anymore, but that's a separate task

**Comment by alfonsobries** [comment]
PR https://github.com/ArkEcosystem/payvo-wallet/pull/1204
