### ISSUE TITLE
[vote page] bottom toolbar not responsive

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1095]
### Describe the refactor you'd like to request

Note that the page in general lacks responsiveness, but that will be a separate task in addition to this one.

The toolbar at the bottom of the vote page is not responsive and simply cuts off any content when the view ends:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/35610748/156768924-c0071347-71ff-4270-a572-e4a29fa883fa.png">

**Comment by alfonsobries** [comment]
Fixed here https://github.com/ArkEcosystem/payvo-wallet/pull/1203
