### ISSUE TITLE
[votes] general responsiveness

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1096]
### Describe the refactor you'd like to request

the vote page has some responsiveness issues on screens < 500px:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/35610748/156769181-9b92b548-cb73-411b-a6b8-07a36952fb7b.png">

**It seems this might be related to the "expanded tables" setting, so making mobile use compact tables at all times may already resolve this issue**

**Comment by goga-m** [comment]
Fixed in https://github.com/ArkEcosystem/payvo-wallet/pull/1203
