### ISSUE TITLE
[wallet details] modals don't fit the user's view

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1099]
### Describe the refactor you'd like to request

Please consider https://github.com/ArkEcosystem/payvo-wallet/issues/1005 before this one!

This may have to do with the wallet details page not being responsive yet, but currently the pages don't fit properly on mobile; they cut off most of the modal's content at the moment. This applies to all modals that can be opened on the wallet details page, so make sure to first resolve the general responsiveness of the page itself before looking at this issue

<img width="412" alt="image" src="https://user-images.githubusercontent.com/35610748/156769879-394f7bd5-f1e4-4dac-89b5-6d726feb4716.png">

**Comment by dated** [comment]
As mentioned above this will be resolved with https://github.com/ArkEcosystem/payvo-wallet/issues/1099.
