### ISSUE TITLE
[settings] profile image text touches delete button

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1110]
### Describe the refactor you'd like to request

When you set a profile image in the settings, you end up having the delete button touching the title . This could benefit from a little more spacing

<img width="115" alt="image" src="https://user-images.githubusercontent.com/35610748/156779942-79ea8c8b-f3ae-42d4-8f84-16d5e009c0b0.png">

**Comment by dated** [comment]
How about reducing the dimensions of the button to 20x20 instead and reduce the negative margins a bit?

![image](https://user-images.githubusercontent.com/6547002/156881460-f3f92538-7017-41c8-bc19-acaed7e50929.png)

This way we wouldn't need to increase the spacing between image and label - which will look slightly off when the `remove` button is not displayed.

**Comment by ItsANameToo** [comment]
yeah that works too
