### ISSUE TITLE
[wallet detail] "my votes" circle gets squashed

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1152]
### Describe the refactor you'd like to request

The circle on the left side gets squashed on screen sizes below 500px

<img width="545" alt="image" src="https://user-images.githubusercontent.com/35610748/157506713-4153d711-4fda-454a-b542-6a2b16ac040d.png">

**Comment by dated** [comment]
Likely covered by #1130.

**Comment by alfonsobries** [comment]
Yeah fixed on https://github.com/ArkEcosystem/payvo-wallet/pull/1136 since it contains a different view on mobile
