### ISSUE TITLE
[Multisig Registration] Transaction fails 

### ISSUE THREAD

**Issue by samharperpittam** [ArkEcosystem/payvo-wallet#990]
### Describe the Bug

when attempting to register a multisignature wallet, the transaction will fail after authentication with the following error:

`{"message":"Cannot read properties of undefined (reading 'id')","type":"TypeError"}` 

### Expected Behavior

Send transaction successfully

### To Reproduce

1. Import multiple wallets on devnet
2. Attempt to register a multisig wallet
3. See error

### What operating system are you using?

macOS

### What browser are you using?

Chrome

**Comment by alfonsobries** [comment]
Should be fixed once [this is released](https://github.com/ArkEcosystem/payvo-sdk/pull/715) and the deps updated
